# Generated by Django 5.0.6 on 2024-06-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('', 'Not defined')], default='', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='case_history',
            field=models.TextField(blank=True, verbose_name='Case history'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('', 'Not defined')], default='', max_length=1, verbose_name='Gender'),
        ),
    ]
