# Generated by Django 5.0.6 on 2024-06-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_reservation', '0003_alter_doctor_email_alter_doctor_national_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
