# Generated by Django 5.0.6 on 2024-07-02 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_reservation', '0004_alter_province_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorspecialty',
            unique_together={('doctor', 'specialty')},
        ),
    ]
