# Generated by Django 5.0.6 on 2024-07-04 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_reservation', '0005_alter_doctorspecialty_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='online_reservation.doctor', verbose_name='Doctor')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='online_reservation.insurance', verbose_name='Insurance')),
            ],
            options={
                'verbose_name': 'Doctor insurance',
                'verbose_name_plural': 'Doctor insurances',
                'unique_together': {('doctor', 'insurance')},
            },
        ),
    ]
