# Generated by Django 5.0.6 on 2024-07-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_reservation', '0006_doctorinsurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('w', 'Waiting'), ('a', 'Approved'), ('na', 'Not approved')], default='w', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='reserve_datetime',
            field=models.DateTimeField(unique=True, verbose_name='Reserve datetime'),
        ),
    ]
