# Generated by Django 5.0.6 on 2024-07-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_reservation', '0007_comment_status_alter_reserve_reserve_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
