# Generated by Django 5.0.6 on 2024-08-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_reservation', '0009_reserve_zarinpal_authority_reserve_zarinpal_ref_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='reserve_datetime',
            field=models.DateTimeField(verbose_name='Reserve datetime'),
        ),
    ]
