# Generated by Django 5.0.6 on 2024-09-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_reservation', '0010_alter_reserve_reserve_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='celery_payment_expiration_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Celery payment expiration datetime'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Celery task_id'),
        ),
    ]
