
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.14-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    container_name: redis
    image: redis:7.2.5-alpine
  
  db:
    image: postgres:16.3-alpine
    container_name: db
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=${DOCKER_COMPOSE_POSTGRES_DB}"
      - "POSTGRES_USER=${DOCKER_COMPOSE_POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${DOCKER_COMPOSE_POSTGRES_PASSWORD}"
      - "POSTGRES_HOST=${DOCKER_COMPOSE_POSTGRES_HOST}"
      - "POSTGRES_PORT=${DOCKER_COMPOSE_POSTGRES_PORT}"

  app:
    image: django_online_reservation
    container_name: app
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
    environment:
      - "DJANGO_DEBUG=${DOCKER_COMPOSE_DJANGO_DEBUG}"
      - "DJANGO_ALLOWED_HOSTS=${DOCKER_COMPOSE_DJANGO_ALLOWED_HOSTS}"
      - "DJANGO_SECRET_KEY=${DOCKER_COMPOSE_DJANGO_SECRET_KEY}"
      - "DJANGO_ZARINPAL_MERCHANT_ID=${DOCKER_COMPOSE_DJANGO_ZARINPAL_MERCHANT_ID}"
      - "POSTGRES_DB=${DOCKER_COMPOSE_POSTGRES_DB}"
      - "POSTGRES_USER=${DOCKER_COMPOSE_POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${DOCKER_COMPOSE_POSTGRES_PASSWORD}"
      - "POSTGRES_HOST=${DOCKER_COMPOSE_POSTGRES_HOST}"
      - "POSTGRES_PORT=${DOCKER_COMPOSE_POSTGRES_PORT}"
      - "JWT_ACCESS_TOKEN_LIFETIME_MINUTES=${DOCKER_COMPOSE_JWT_ACCESS_TOKEN_LIFETIME_MINUTES}"
      - "JWT_REFRESH_TOKEN_LIFETIME_MINUTES=${DOCKER_COMPOSE_JWT_REFRESH_TOKEN_LIFETIME_MINUTES}"
    depends_on:
      - db
      - redis
      - rabbitmq

  celery:
    container_name: celery
    command: celery --app=config worker -l INFO -Q tasks
    build: .
    volumes:
      - .:/app/
    environment:
      - "DJANGO_CELERY_BROKER_URL=${DOCKER_COMPOSE_DJANGO_CELERY_BROKER_URL}"
      - "DJANGO_CELERY_RESULT_BACKEND=${DOCKER_COMPOSE_DJANGO_CELERY_RESULT_BACKEND}"
      - "POSTGRES_DB=${DOCKER_COMPOSE_POSTGRES_DB}"
      - "POSTGRES_USER=${DOCKER_COMPOSE_POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${DOCKER_COMPOSE_POSTGRES_PASSWORD}"
      - "POSTGRES_HOST=${DOCKER_COMPOSE_POSTGRES_HOST}"
      - "POSTGRES_PORT=${DOCKER_COMPOSE_POSTGRES_PORT}"
    depends_on:
      - app

  flower:
    image: mher/flower
    container_name: flower
    ports:
      - "5555:5555"
    environment:
      - "CELERY_BROKER_URL=${DOCKER_COMPOSE_DJANGO_CELERY_BROKER_URL}"
      - "FLOWER_UNAUTHENTICATED_API=true"
    depends_on:
      - celery

# volumes:
#   postgres_data:
